spring.application.name=eventmanager

springdoc.swagger-ui.url=/openapi.yaml

spring.datasource.password=root
spring.datasource.username=project
spring.datasource.url=jdbc:postgresql://localhost:5431/EventManager

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

server.port=8085

kafka.notification-topic=event-notification

token.lifetime=18000000000
token.signature=b6b458da-d1b3-412d-93ca-a6cead5eb94f

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

event.status.cron = 0 * * * * *

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

spring.cache.type=redis

spring.profiles.active=dev
